### ISSUE TITLE
Low accuracy in classification in target test dataset

### ISSUE THREAD

**Issue by AI-Nature** [AINature/Classification-models#2]
Previously I decided to use MobileNet with its brief architecture to run the classification task. In the newly published dataset with target test data, the accuracy dropped and is not satisfying.

**Comment by szseyd** [comment]
I proposed to use ResNet instead of MobileNet, with kind of more complex architecture but still considerable efficiency to increase the accuracy in classification.  But here I faced to a new issue that I will try to discuss separately.
